---
- hosts: localhost
  gather_facts: no
  tasks:
    - name: Ensure Apache is installed
      yum:
        name: httpd
        state: present

    - name: Ensure Apache is running
      service:
        name: httpd
        state: started
        enabled: yes

    - name: Create a simple index.html page
      copy:
        content: "Testing successful, deployment complete. Web server is now up and running."
        dest: /var/www/html/index.html

    - name: Ensure Apache is configured to serve the index.html page
      file:
        path: /var/www/html/index.html
        state: file
        mode: '0644'
